### ISSUE TITLE
Prepoznavanje znakovnih slova gluvonemih osoba u realnom vremenu

### ISSUE THREAD

**Issue by milosrs** [ftn-ai-lab/sc-2017-e2#1]
**Članovi tima:** 
- Miloš Ribar  RA171/2014
- Milan Hinić RA167/2014

**Problem koji se rešava (detaljniji opis)**
- Koristeći web-kameru kompjutera, prepoznavaćemo slova znakovnog alfabeta gluvonemih osoba. Potrebno je uperiti kameru u osobu koja koristi znakovni alfabet, a program će ispisivati koje je slovo osoba pokazala.

**Algoritam/algoritmi koji će se koristiti**

- Dilatacija i erozija slike
- Haar Cascades za prepoznavanje lica
- Konvolucione neuronske mreže za prepoznavanje šake i slova koje je osoba pokazala

**Metrika za poređenje performansi algoritama i/ili parametara algoritma**

- Unapred će biti poznato šta treba da bude izlaz. Imaćemo poseban deo programa koji će ispisivati koje je slovo osoba pokazala, i sa kojom sigurnošću je sistem ispisao rešenje.

**Podaci koji se koriste**

- Podaci su dostupni online. Za prepoznavanje šake i slova iz alfabeta, koristićemo dataset koji skinemo sa interneta. 

**Na koji način planirate validaciju rešenja?**

- Konvoluciona neuronska mreža treba da bude istrenirana u tolikoj meri da može da prepozna različita slova iz alfabeta. Na osnovu slika, može se videti da li je rešenje tačno. Moraćemo da registrujemo pokrete ruke da bi smo razlikovali slučajeve u kojima osoba drži jedan isti znak duže vremena, ili je došlo do pokreta ruke i pokazivanja ponovo istog znaka. Merićemo razdaljinu između jedne i druge šake i tako ćemo registrovati pokrete.
Validaciju ćemo vršiti manuelno, koristeći kameru. Pokazivaćemo razna slova i program bi trebao da ispiše sa kojom sigurnošću je klasifikovao ono što smo pokazali.

Asistent: @StefanAndjelic 
Repozitorijum: https://github.com/milosrs/FingerSpelling

**Comment by StefanAndjelic** [comment]
Tema odobrena.
Jedino možete još malo da opišete kako nameravate da pristupite validiranju rešenja, odnosno merenju tačnosti.
