### ISSUE TITLE
Rešvanje SUDOKU-a na osnovu slike

### ISSUE THREAD

**Issue by VladimirJovicic** [ftn-ai-lab/sc-2017-e2#10]
**Članovi tima**

- Vladimir Jovičić RA 218 / 2014

- Marko Krajinović RA 80 / 2014

**Problem koji se rešava  :** 

- Na osnovi učitane slike sudoku-a, program kao output šalje matricu rešenog sudoku-a

**Algoritam koji će se koristiti : **

- Algoritam koji će da se koristi je backtrack

**Dataset**

- Ima postojeći dataset na internetu koji se sastoji iz gomile slika brojeva od 1 do 9 različitih oštrina i fontova kao i niza slika "praznina" koji će služiti za prepoznavanje praznih polja sudoku matrice

**Github repozitorijum**

- https://github.com/VladimirJovicic/SOFT

**Asistent**

- @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Backtrack koristite za rešavanje same sudoku puzle. Kakav će biti pristup za prepoznavanje vrednosti sa slike? Takođe u kakvoj perspektivi su slike?

**Comment by VladimirJovicic** [comment]
Da backtrack smo i hteli da koristimo za rešavanje..
Nismo još sigurno koji bi algoritam koristili za prepoznavanje jer ne znamo koji sve postoje i koji bi bio optimalan i šta znači u kakvoj su perspektivi slike?
@StefanAndjelic

**Comment by StefanAndjelic** [comment]
Na primer slika može biti slikana ukoso, ili pak direktno normalno na sudoku puzlu. Ni ne morate da postavite tačan algoritam ali bi bilo dobro da rešite ograničenja sistema. Pošto vas je dvojica, bilo bi dobro da podržite slike slikane iz nekog ugla. Na primer: ![sudoku](https://www.cs.bgu.ac.il/~ben-shahar/Teaching/Computational-Vision/StudentProjects/ICBV131/ICBV-2013-1-BorisSpektor/src/puzzles/sudoku2.jpg)

**Comment by VladimirJovicic** [comment]
Pa dobro, potrudićemo se da napravimo da radi i za takve malo ukošene slike, ali pošto nismo planirali još da krenemo, nismo se još tačno dogovorili koji bi algoritam koristili a rešavanje prepoznavanja brojeva tj. cele matrice
@StefanAndjelic
