### ISSUE TITLE
Prepoznavanje lica

### ISSUE THREAD

**Issue by tulac** [ftn-ai-lab/sc-2017-e2#108]
**Grupa 5**
**Članovi tima:**
Olja Anđelovski RA162-2014
Stefan Tulać RA131-2014

**Asistent**: Miroslav Kondić

**Cilj projekta je prepoznavanje lica određene osobe.** 

**Koraci u implementaciji:**
- Prikupljanje fotografija lica osobe koju želimo da identifikujemo
- Treniranje na osnovu fotografija lica osobe i imena respektivno
- Prepoznavanje (da li prepoznaje ono za šta je treniran)

**Za detekciju lica koristićemo:**
- cv2.face.createEigenFaceRecognizer()
- cv2.face.createFisherFaceRecognizer()
- cv2.face.createLBPHFaceRecognizer()

**Sakupljanje podataka:** Manuelno

**Validacija rešenja:** Empirijski

**Repozitorijum:** https://github.com/tulac/soft

**Pomoć pri realizaciji:**
_https://docs.opencv.org/2.4/modules/contrib/doc/facerec/facerec_tutorial.html#face-recognition
http://hanzratech.in/2015/02/03/face-recognition-using-opencv.html
https://thecodacus.com/opencv-face-recognition-python-part1/#.Wk-ZLainFPY_

**Comment by miroslavftn** [comment]
Tema odobrena. U zavisnosti od skupa podataka i kompleksnosti slika bice odredjena maksimalna ocena projekta.
