### ISSUE TITLE
Klasifikacija voća i povrća na zdrave i bolesne

### ISSUE THREAD

**Issue by neven95** [ftn-ai-lab/sc-2017-e2#117]
- **Članovi tima:**

    Neven Jović ra18/2014,
    Nikola Skrobonja ra25/2014,
   Grupa10

- **Detaljniji opis problema:**
   Klasifikacija voća i povrća na trule i zdrave. Na osnovu slike voća ili povrća određuje se da li je biljka 
   trula ili je zdrava. U poljoprivredi se sve više koristi klasifikacija proizvoda radi razlike u cenovnom 
   rangu izmedju kvalitetnih i ne kvalitetnih.

- **Algoritmi koji se koriste:** 
   Koristiće se dva tipa rešavanja problema i kasnije će se porediti efikasnost oba. 
      1.  Prvi način će biti preko "Transfer learning" tehnike u kojoj će biti korisćen predtrenirani CNN model koji je istreninran na osnovu podataka sa imageNeta i sa čijeg ćemo izlaza koristiti podatke da istreniramo full connected neuronsku mrežu.
      2.  Drugi način će biti korišćenjem OpenCV biblioteke i segmentacija boja i full connected neuronske mreže.

- **Metrika za poređenje performansi:** 
   Koristićemo ugrađenje  alate iz biblioteka koji određuju uspešnost modela (npr. cross validation).

- **Podaci koji će se koristiti:** 
   Koristićemo slike koje ćemo skinuti sa Google Images, labelirati i obraditi pre primene. 

Repozitorijum:  https://github.com/neven95/soft-computing
Asistent: Ivan Perić, @ivan7792

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

U prijavi ste napisati da koristite KNN model. Pretpostavljam da je u pitanju konvolutivna neuronska mreža (CNN), a ne KNN model (k najbližih suseda). Ispravite taj deo da se drugi studenti ne zbune čitajući prijavu.
