### ISSUE TITLE
Prepoznavanje emocija na licu u realnom vremenu

### ISSUE THREAD

**Issue by tttamara23** [ftn-ai-lab/sc-2017-e2#12]
**Clanovi tima:**

- Marko  Vuckovic, RA135/2014, grupa 7
- Tamara Perlinac, RA137/2014, grupa 7
- Asistent: Ivan Peric @ivan7792 

**Problem koji se resava:**

- Prepoznavanje emocija na licu u realnom vremenu, na osnovu videa.

**Algoritam koji ce se koristiti za resavanje problema:**

- Za prepoznavanje lica koristice se dlib OpenCV biblioteka(uzimace se u obzir tacke koje su oko ociju, usana i obraza), a za resavanje samog problema prepoznavanja emocija koristice se neuronska mreza i KNN algoritam. Pomocu canny algoritma ce se detektovati ivice u odredjenim delovima lica kako bi se poboljsalo prepoznavanje emocija(na primer, naborana koza izmedju ociju upucuje na to da je osoba ljuta, itd..).

**Metrika za poredjenje performansi algoritama:**

- Video je niz slika, pa ce se racunati procenat slika na kojima su emocije tacno prepoznate.

**Podaci koji se koriste:**

- Koristice se dataset koji je dostupan online.

**Nacin validacije resenja:**

- Validacija resenja ce se vrsiti nad snimcima koji se ne nalaze u dataset-u nad kojim je neuronska mreza obucavana.

**Link ka repozitorijumu:**
https://github.com/tttamara23/softComputing2018

**Comment by ivan7792** [comment]
Tema odobrena.

Par pitanja i sugestija pre nego što krenete sa radom:

- Koje tačke lica planirate koristiti - sve ili neke specificne?
- Za maksimalnu ocenu probajte naći dataset i probati više različitih pristupa (ne samo VNM, ne samo tačke lica nego i neke druge osobine - recimo bore i neke druge elemente koji mogu pokazati emociju).

Istu temu radi i Vukašin (https://github.com/ftn-ai-lab/sc-2017-e2/issues/29), koji uključuje i DeepLearning pristup, pa se možete spojiti i odraditi projekat u timu od troje.

**Comment by tttamara23** [comment]
Uzeli smo u obzir sugestije i issue je ispravljen.
