### ISSUE TITLE
Detektor kože kod ljudi

### ISSUE THREAD

**Issue by lazicmiljana** [ftn-ai-lab/sc-2017-e2#13]
**Ko su članovi tima? Ime, prezime, broj indeksa...**
Miljana Lazić (RA117/2014) i Nevena Ristanović (RA116/2014)

**Problem koji se rešava (detaljniji opis)**
Rešavaćemo problem detektovanja ljudske kože sa slike. Vršiće se segmentacija regiona na željenoj slici u cilju prepoznavanja. Razmatraće se svaki piksel slike i gledati da li je u pitanju piksel kože ili ne. 

**Algoritam/algoritmi koji će se koristiti**
Naïve Bayes za klasifikaciju 

**Metrika za poređenje performansi algoritama i/ili parametara algoritma**
Osnovna metrika će biti verovatnoća koja je izračunata pomoću Bajesove teoreme, a pokazuje da je neki piksel upravo piksel kože ili ne.

**Podaci koji se koriste - da li su već dostupni online, da li će se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi?**
Koristićemo data set-ove sa slikama ljudi, a oni će biti kreirani kombinacijom par data set-ova koji su dostupni online.

**Na koji način planirate validaciju rešenja?**
Validacija će biti izvršena pomoću data set-a koji je izdvojen za testiranje.

**Repozitorijum:** 
https://github.com/lazicmiljana/SoftComputing

Asistent: Ivan Peric @ivan7792

**Comment by ivan7792** [comment]
Pozdrav koleginice,

Ovo nije odgovarajuća tema za Soft kompjuting. Bila bi pogodna za ORI.

Izaberite nešto iz oblasti računarske vizije, gde ćete raditi sa obradom slike i primeni ovakvih ili sličnih algoritama sa ORI i SOFT na slici, pa ispravite issue. Pošto ja kasnim sa odgovorom, imate vremena do ponedeljka sledeće nedelje da to uradite.

**Comment by ivan7792** [comment]
Izmenjena tema sada odgovara sadržaju predmeta, ali je sama kompleksnost relativno nepoznata. U svakom slučaju, tema je odobrena i srećan rad.

Obratite pažnju na sledeće stavke od kojih zavisi koliko je projekat kompleksan, a posledično i za koju je ocenu:

- Da li prepoznajete samo jednu rasu ljudi, ili više njih.
- Da li detektujete samo kožu lica ili celog tela.
- Da li planirate neku dodatnu analizu dobijenih rezultata? Sigurno ćete imati gomilu piksela koji su klasifikovani kao koža, iako se nalaze na sasvim slučajnim pozicijama na fotografijama.
- Čak i ako nađete slike ljudi sa interneta, morate sami obeležiti kožu i ono što nije koža, a to će zahtevati dodatni posao koji se ne računa u kompleksnost projekta. Super je ako imate označen dataset, ali mi se ne čini da je tako iz same prijave.

Od ovih stavki zavisi sama maksimalna ocena koju možete dobiti. S obzirom na činjenicu da radite u timu, za ocenu višu od 6-7 morate imati neki vid dodatne analize nakon same klasifikacije piksela, pored same klasifikacije (koja je trivijalna ako imate skup podataka).
