### ISSUE TITLE
Detekcija cvetova sa slike i brojanje latica

### ISSUE THREAD

**Issue by deekscitacija** [ftn-ai-lab/sc-2017-e2#15]
### **Članovi tima :**

- Igor Trpovski RA 71/2014
- Marija Joksimović RA 58/2014

### **Problem koji se rešava?**

Rešavaće se problem detekcije cvetova na slici i brojanja latica na svakom od njih.
Potrebno je prvo prepoznati sve cvetove sa slike, a zatim obučiti neuronsku mrežu da zaključi koliko latica ima na svakom prepoznatom cvetu.

### **Algoritmi koji će se koristiti?**

1. Upotrebili bismo segmentaciju za detekciju regiona u kojima se nalazi jedan cvet, dok ne detektujemo sve cvetove sa slike.
2. Konvoluciona neuronska mreža.

### **Metrika za poređenje performansi algoritama :** 

Prema broju tačno prepoznatih cvetova na slici i broju latica na svakom od njih.

### **Podaci koji se koriste ?**
 
Kombinacija podataka preuzetih sa interneta i fotografija koje ćemo sami prikupiti. 
Podatke će možda biti potrebno prethodno obraditi.

### **Validacija rešenja :** 

Imaćemo označen data-set u kom je unapred definisan broj latica za svaki cvet. Naši test primeri će sadržati više cvetova, uz mogućnost postojanja i drugih objekata na slici. 
Preciznost ce biti iskazana u procentima, koji predstavljaju stepen poklapanja izbrojanih latica na svakom detektovanom cvetu.

Repozitorijum : https://github.com/trpelonski/Soft-Computing

Asistent : @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena, uz obavezan fokus na segmentaciji više vrsta cvetova. Srećan rad!
