### ISSUE TITLE
Predefinisani projekat za 40 bodova (ocene 7 i 8)

### ISSUE THREAD

**Issue by DanijelaZel** [ftn-ai-lab/sc-2017-e2#18]
**Student:** Danijela Zelenović, RA72/2014

**Definicija problema:**
* Izvršiti sabiranje svih cifara koje prolaze ispod linije
* Liniju detektovati korišćenjem Hough transformacije
* Postići tačnost prepoznavanja od bar 90%

**Repozitorijum:** https://github.com/DanijelaZel/SoftComputing

**Asistent:** Miroslav Kondić @miroslavftn

**Comment by miroslavftn** [comment]
Tema odobrena.
