### ISSUE TITLE
Predefinisani projekat za 40 bodova (ocene 7 i 8)

### ISSUE THREAD

**Issue by Sreten95** [ftn-ai-lab/sc-2017-e2#19]
Student: Sreten Petrovic RA75-2014

Sabiranje svih cifara koje prođu ispod linije. Potrebno je liniju detektovati korišćenjem Hough transformacije.

Repozitorijum : https://github.com/Sreten95/SOFT

Asistent : Miroslav Kondic @miroslavftn

**Comment by miroslavftn** [comment]
Tema odobrena.
