### ISSUE TITLE
Prepoznavanje pobednika na atletskoj stazi

### ISSUE THREAD

**Issue by 50pace** [ftn-ai-lab/sc-2017-e2#2]
**1. Tim:**

    1. Nemanja Mudrinić RA 114/2014 git: @sansajn5
    2. Stefan Pačavra RA 183/2014 

**2. Definicija problema:**

   1.Prepoznavanje trkača na atletskoj stazi koji je prvi ušao u cilj. 

**3. Motivacija problema:**

   Zbog reuglarnosti  i tačnosti odredjivanja pobednika na atletskim trkama, i kako bi se omogućio manji posao sudijama a samim tim u pomoć u donošenju odluka. 

**4. Skup podataka :**
   1. Skup podataka planiramo sami da konstruišemo, skidanjem snimaka atletskih trka na 100m                 sa youtube-a.  
    

**5. Metodologija rešavanja  Prati sledeće korake:**
   1. Učitavanje videa atletske trke ;
   2. Detekcija staze;
    3. Izdvajanje trkača u odnosu na stazu u kojoj se nalazi ;
   4. Označavanje prva tri trkača u cilju ;
  

**6. Metod evaluacije :** 
   1. Koristićemo regresiju kao metod za predikciju ;
   2. Za validaciju ćemo koristiti podatke koji ce predstavljati tačne rezultate trka.

**Asistent**: @StefanAndjelic 
repozitorijum: https://github.com/sansajn5/EagleEye/projects

**Comment by StefanAndjelic** [comment]
Tema je u redu, morate samo biti specifičniji sa datasetom. Pošto znam da nije isuviše zastupljena stvar kada su u pitanju kontrolisani uslovi za snimak.

**Comment by 50pace** [comment]
Hvala na odgovoru.
Mi smo razmisljali da skidamo snimke sa youtube-a ali ne znamo koliko je doboljno?

**Comment by StefanAndjelic** [comment]
Broj snimaka prvenstveno zavisi od pristupa. Za neke pristupe je dovoljno svega par snimaka. Sa druge strane bilo bi dobro imati i nekoliko validacionih snimaka.
Veći problem može da napravi nekonzistentnost između snimaka.
