### ISSUE TITLE
Generisanje slike osobe na osnovu tekstualnog opisa

### ISSUE THREAD

**Issue by ilijagrbic** [ftn-ai-lab/sc-2017-e2#20]
## Članovi tima:
- Milan Stanković (RA161-2014)
- Ilija Grbić (RA16-2014)
## Problem koji se rešava:
Korisnik unosi opis izgleda lica osobe (npr. duzina kose, boja kose, boja ociju itd.), a aplikacija generise odgovarajucu sliku (portret) za taj opis.
## Algoritmi koji će se koristiti:
- Za obucavanje dela koji prepoznaje značenje u rečenici koristićemo rekurentnu neuralnu mrežu
- Za deo koji generise slike koristićemo GAN (Generative adversarial network)
## Metrika za poređenje performansi algoritama i/ili parametara algoritma
Procena uspesnosti algoritma ce se vrsiti poredjenjem u kojoj meri je algoritam ispostovao zadate parametre pri generisanju slike.
## Podaci koji se koriste:
Koristićemo jedan od datasetova za face recoginition dostupnih online.
## Na koji način planirate validaciju rešenja?
Validacija ce biti resena poredjenje slike koju smo ocekivali da dobijemo i generisane slike.

Asistent: @miroslavftn 
Repozitorijum:https://github.com/Milan-Stankovic/Soft-computing

**Comment by miroslavftn** [comment]
Tema odobrena.
