### ISSUE TITLE
Predefinisani projekat za 40 bodova (ocene 7 i 8)

### ISSUE THREAD

**Issue by babycatatonia** [ftn-ai-lab/sc-2017-e2#22]
Student: Stefan Bubanj RA166/2013

Definicija problema:

Izvršiti sabiranje svih cifara koje prolaze ispod linije
Liniju detektovati korišćenjem Hough transformacije
Postići tačnost prepoznavanja od bar 90%
Repozitorijum: https://github.com/babycatatonia/sc17-18

Asistent: Miroslav Kondić @miroslavftn

**Comment by miroslavftn** [comment]
Tema odobrena.
