### ISSUE TITLE
Predefinisani projekat za 60 bodova (ocene 9 i 10)

### ISSUE THREAD

**Issue by Kosticeva** [ftn-ai-lab/sc-2017-e2#23]
Student:  Jelena Kostić, RA81/2014
Definicija problema: 

- Detektovanje pokretnih linija sa video zapisa,

- Prepoznavanje brojeva koji prolaze iza pokretnih linija,

- Cifre koje prođu ispod prve linije treba sabrati, a cifre koje pređu ispod druge linije treba oduzeti od konačnog rezultata.

Metodologija: 

- Za detektovanje pokretnih linija biće korišćena Hough-ova transformacija.

Repozitorijum: https://github.com/Kosticeva/sc2017-digit-detection

Asistent: @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena!
