### ISSUE TITLE
Detekcija i prepoznavanje saobraćajnih znakova

### ISSUE THREAD

**Issue by marijakukic** [ftn-ai-lab/sc-2017-e2#24]
## Članovi tima

- Aleksandar Lupić RA33-2014 Grupa: 9
- Marija Kukić RA124-2014 Grupa: 2
- Repozitorijum : https://github.com/marijakukic/SoftComputing
- Asistent : Ivan Perić @ivan7792

### Opis problema

- Ovim projektom bavićemo se detekcijom, prepoznavanjem i klasifikacijom saobraćajnih znakova nad datim skupom podataka. Implementacija algoritma će na osnovu prethodno unetih slika različitih znakova, obradom slike / video zapisa vršiti detekciju saobraćajnih znakova i na osnovu oblika klasifikovati ih u odgovarajuću grupu (znakovi opasnosti, obaveštenja i izričitih naredbi). 

### Cilj rešavanja problema

- Cilj je da se izvrši prepoznavanje znaka iz skupa prosleđenih slika, kao i da se izvrši njegova klasifikacija u određenu grupu znakova, ostvarujući očekivanu (adekvatnu) procentualnu tačnost.

## Algoritam koji će se koristiti

- OpenCV i odabrani framework (TensorFlow, Keras...) za kreiranje konvolucione neuronske mreže

- K-means algoritam za klasifikaciju saobraćajnih znakova

## Metrika za poređenje performansi algoritma

- Prilikom analiziranja videa iz saobraćaja znaćemo ukupan broj znakova koji bi trebali biti prepoznati. Brojaćemo detektovane i prepoznate znakove , čiju ćemo krajnju sumu porediti sa očekivanim brojem.
Prema broju tačno prepoznatih znakova računaćemo procentualnu tačnost.
## Podaci koji se koriste

Skup podataka predstavljaju slike i video koji su dostupni online.

- Snimci iz saobraćaja [Video](http://www.cvlibs.net/datasets/kitti/index.php)

- Skup slika za detekciju znakova, znakova u okruženju [Data set detection](http://benchmark.ini.rub.de/?section=gtsdb&subsection=dataset)

- Skup slika za prepoznavanje znakova, izdvojeni saobraćajni znakovi [Data set recognition](http://benchmark.ini.rub.de/?section=gtsrb&subsection=news)

## Validacija rešenja

- Validacija će se vršiti empirijski za svaki znak pojedinačno, uočavanjem i poređenjem da li je znak detektovan, zatim klasifikovan i prepoznat na željeni način.  Efikasnost mreže ispitaćemo računajući procentualnu preciznost nad obučavajućim skupom podataka i testiranjem nad testnim skupom podataka za prepoznavanje koje nisu bile deo obučavajućeg skupa.

**Comment by ivan7792** [comment]
Par pitanja i komentara:

- U algoritmima za korišćenje ste napisali da radite klasifikaciju KMeans algoritmom. Kmeans je tipičan predstavnik algoritma za klasterizaciju, a ne za klasifikaciju. Razlika je velika pošto u jednom slučaju imate označene podatke a u drugom ne. Da li radite klasterziaciju ili klasifikaciju?

- Da li pre klasifikacije/klasterizacije znakova planirate neku obradu slike znaka i na koji način?


Inače, ova tema je obrađivana prethodnih godina, pa vodite računa da ne uzimate kod od starijih kolega da bi izbegli situaciju sa plagiranjem. Nakon što ispravite navedene stvari tema će biti odobrena. Srećan rad.

**Comment by marijakukic** [comment]
Radićemo klasifikaciju znakova za šta ćemo koristiti k-Nearest Neighbors algoritam. Obrada slike će biti neophodna radi izdvajanja oblika saobraćajnog znaka odnosno izdvajanja saobraćajnog znaka od okoline i obuhvataće segmentaciju slike (grayscale,odredjivanje tresholda,izdvajanje regiona od interesa).
