### ISSUE TITLE
Detekcija i prepoznavanje registarskih tablica

### ISSUE THREAD

**Issue by ivukasinovic** [ftn-ai-lab/sc-2017-e2#26]
## Članovi tima :
•	Ivan Vukašinović RA53/2014
•	Dejan Stojkić RA177/2014

## Problem koji se rešava:
Detekcija i prepoznavanje registarskih tablica automobila na video snimku u realnom vemenu . Prvi problem jeste detekcija vozila i izdvajanje tabilca sa registrovanih objekata (vozila) za dati snimak. Zatim kada je tabilica detektovana izdvajaju se karakteri sa date tablice .  
Rešenje može biti korišćeno u razne svrhe gde je potrebna automatska detekcija tablica (npr. kod parking servisa (kamere na ulazu pored rampe) , naplatne rampe na autoputu , za potrebe policije detektovanja tablica vozila ). 

## Algoritmi koji će se koristiti:
Adaptivni thresholding za filtriranje slike . Izdvajanje dela na kojem se nalazi tablica i njegova obrada  za konvolucionu neuronsku mrežu (OCR) .
Koristili bismo OpenCV biblioteku na Python programskom jeziku i njene mogućnosti u real time režimu. ( https://www.youtube.com/watch?v=iS_yuSEFXxM slicno )

## Metrika za poređenje performansi algoritama :
Metrika će biti preciznost tačno prepoznatih (karaktera) tablica na osnovu tačnih vrednosti tablica iz određenog fajla u kome se nalaze podaci o tablicama datih vozila. Broj tačno prepoznatih tablica, porediće se rešenje sa fajlom koji sadrži podatke na osnovu videa. 

## Podaci koji se koriste:
Video snimak koji samo napravili ili je preuzet sa interneta. Koristićemo dataset za obučavanje neuronske mreže koji se sastoji iz karaktera.

## Validacija rešenja:
Broj tačno prepoznatih tablica, porediće se rešenje sa fajlom koji sadrži podatke na osnovu videa.

**Comment by ivan7792** [comment]
Tema odobrena.

Ova tema je obrađivana jako veliki broj puta prethodnih godina. Obratite pažnju da ne uzimate gotove implementacije sa interneta da ne bi imali plagiran projekat. Odradite samostalno sve što možete.
