### ISSUE TITLE
Generisanje novih DBS likova na osnovu postojećih korišćenjem GAN

### ISSUE THREAD

**Issue by StefanCepa** [ftn-ai-lab/sc-2017-e2#28]
##  **Članovi tima:**
_Stefan Radonjić (RA245-2014)
Marko Jurić (RA86-2014 )_
**Asistent**: _Miroslav Kondić_
**Repozitorijum**: https://github.com/StefanCepa/generating-dbs-characters

##  **Problem koji se rešava:**
_ Generisanje novih Dragon Ball Super karaktera na osnovu postojećih._ 

## **Algoritmi koji će se koristiti:**
_ Za generisanje do sada ne vidjenih Dragon Ball Super karaktera koristićemo Generative Adversarial Network (GAN)._
 
## **Metrika za poređenje performansi algoritama i/ili parametara algoritma**
_ Uspešnost algoritma će biti vršena na prema meri u  kojoj je algoritam ispoštovao prosleđene parameter prilikom generisanja slike._

##  **Podaci koji se koriste:**
_ Trenutno ne postoji dostupan skup nama potrebnih podataka tako da ćemo biti primorani da kreiramo naš dataset korišćenjem Google-ovog sistema pretrage slika ( Google Images )  ._

## **Na koji način planirate validaciju rešenja?**
_ Validaciju rešenja ćemo vršiti poređenjem slika unutar našeg skupa podataka sa generisanim slikama, odnosno biće mera u kojoj je Generator uspeo da "prevari" Diskriminator._

**Comment by miroslavftn** [comment]
Tema odobrena. Imam nekoliko pitanja. 

- za klasifikaciju cega planirate da koristite CNN
- zasto kreirate sami skup podataka? Sigurno se moze pronaci online skup
- od kvaliteta samih slika, odnosno tezine ocitavanja cifara ce vam zavisiti ocena (ako su slike dobrog kvaliteta i sve imaju slican font, svodi se na OCR koji je radjen na predavanju/vezbama)
- da li ce cifre biti digitalne ili fotografisane kao npr brojevi kuca i sl..

**Comment by StefanCepa** [comment]
Napravicemo posebnu skriptu koja ce nam automatski skinuti slike sa interneta na disk. Odlucili smo se da sami kreiramo dataset jer smo pronasli program koji dinamicki generise novu CAPTCHA sliku na refresh stranice. S toga cemo se koristiti Python bibliotekom "requests" koja ce nam omoguciti da ostvarimo HTTP konekciju i izvrsimo GET zahtev. 
Slike koje budemo skidali izgledaju ovako:

![image](https://user-images.githubusercontent.com/29452007/34535172-778e4834-f0c1-11e7-9bf3-d95be7da03e4.png)

S obzirom da sami pravimo dataset, i na cinjenicu da je podatke unutar dataset-a potrebno obeleziti kako bi CNN bila sposobna da uci i izvrsi korekciju prilikom procesa za trening, nas zadatak je da predprocesujemo svaku od ovih slika tako sto cemo  koriscenjem Computer Vision tehnika izdvojiti brojeve sa slike, izgenerisati odgovarajucu labelu za svaki od brojeva i smestiti ih u odgovarajuce direktorijume ( direktorijumi od 0 do 9 ).
Drugim recima moracemo da extract-ujemo regione od interesa ( ROI ) sa slike i rasporedimo ih u odgovarajuce direktorijume.
