### ISSUE TITLE
Razlika između konvencijalnog i modernog pristupa za prepoznavanje emocija

### ISSUE THREAD

**Issue by vmicic** [ftn-ai-lab/sc-2017-e2#29]
**Ko su članovi tima?**

Vukašin Mićić RA 118/2014, grupa 3

**Problem koji se rešava?**

Rešava se problem prepoznavanja emocija na osnovu date slike lica. Biće upoređeni rezultati konvencijalnog pristupa koji prepoznaje emocije na osnovu važnih tačaka lica, sa modernim pristupom koji koristi konvolutivne neuronske mreže za prepoznavanje.

**Algoritmi**

Konvolutivne neuronske mreže, HOG.

**Metrika**

Metrika će predstavljati procenat tačno prepoznatih emocija.

**Podaci koji se koriste?**

fer2013 dataset

**Na koji način planirate validaciju rešenja?**

Postojaće validacioni set na osnovu kojeg se vrši validacija.

**Repozitorijum:**

https://github.com/vmicic/Emotion-Recognition

**Asistent**: Ivan Peric

**Comment by ivan7792** [comment]
Tema odobrena.

Ostaviti link ka repozitorijumu i ka skupu podataka. 

Pogledati komentar ostavljen na https://github.com/ftn-ai-lab/sc-2017-e2/issues/12.
