### ISSUE TITLE
Prepoznavanje Magic the Gathering karata

### ISSUE THREAD

**Issue by BoraLucifer** [ftn-ai-lab/sc-2017-e2#3]
**Članovi tima:** Mihailo Mandić RA 176/2014, Boris Pešić RA 97/2014.

**Problem:** Prepoznavanje Magic the Gathering karte na osnovu imena karte.

**Algoritmi:** Radi obrade slike biće upotrebljeni algoritmi kao što su: morfološke operacije, izdvajanje regiona, algoritam za izdvajanje kontura sa slike i detektovanje ivica na slici.

**Metrika za poređenje performansi algoritama:** Tačno ine prepoznate karte na osnovu njnog imena.

**Podaci:** Skup (data set) koji se sastoji od oko 13000 karata.

**Validacija:** Validacija će biti odradjena pomoću data seta, ona će služiti da proverimo da li je aplikacija tačno prepoznala kartu uz pomoc korišćenja Levenstein metode.

Link ka repozitorijumu:
https://github.com/BoraLucifer/MekaniKompjuting

@ivan7792

**Comment by ivan7792** [comment]
Koji pristup koristite:

- Da li prepoznajete koja je karta u pitanju tako što iz liste svih mogućih karata (fotografije) tražite najsličniju, (može biti za maksimalnu ocenu, ali po trenutnom opisu mi se čini da je za 6-7)?

- ili čitate Ime, Rules text, Mana cost, Card type sa fotografije karte i na osnovu toga vršite klasifikaciju? U drugom slučaju, šta koristite za prepoznavanje cifara i znakova - neku biblioteku ili sami obučevate i trenirate neki klasifikator? Ovaj pristup je za maksimalnu ocenu.

Ovaj problem je već rešavan ranijih godina, pa obratite pažnju da ne uzimate gotova rešenja sa interneta da ne bi imali plagiran projekat.

Tema odobrena, srećan rad.
