### ISSUE TITLE
Čitač stripova

### ISSUE THREAD

**Issue by jowookoh** [ftn-ai-lab/sc-2017-e2#32]
**TIM**
Vuko Jovičić RA188/2013

**Definicija problema**
Prepoznavanje teksta i identiteta glavnih junaka (ima ih 7) u domaćem izdanju stripa Alan Ford, i pripajanje odredjenog "oblačića" odgovarajućem junaku. 
Problem za koji ću sam morati da smislim rešenje je taj - kom akteru pripada koji oblačić

**Motivacija**
U unapredjenoj verziji, koju neću realizovati za potrebe ovog projekta, aplikacija bi podrazumevala Text to speech sistem i neku vrstu animacije (oživljavanja) aktivnog govornika - ova aplikaciju mogla bi koristiti deca koja još ne umeju da čitaju.

**Skup podataka**
Skup od 50 brojeva Alan Ford stripa, svaki sa po više od 100 strana, u pdf formatu.
U pripremanju data seta ću pokušati sebi da olakšam koristeći openCV i isecati likove koji će mi biti potrebni za trening set.

**Algoritmi i metodologija**
Za prepoznavanje teksta - OCR sistem (CNN)
Za prepoznavanje aktera - Konvolucione neuronske mreže uz podršku tensorflow, keras i drugih paketa.
Za detektovanje regija od značaja - verovatno samo openCV (viola-jones algoritam ili nešto slično)

**Repozitorijum** 
https://github.com/vukojovicic/comic-reader

**Comment by StefanAndjelic** [comment]
Tema odobrena! Srećan rad
