### ISSUE TITLE
Predefinisani projekat za 20 bodova (ocena 6)

### ISSUE THREAD

**Issue by sstefox** [ftn-ai-lab/sc-2017-e2#33]
Student: Stefan Stanković RA241/2013

Definicija problema:
Izvršiti prebrojavanje ljudi koji se u barem jednom trenutnku nađu na platou. Potrebno je postići tačnost od bar 60%.

Skup koji se koristi: https://drive.google.com/drive/folders/1qjwIKAXpYz45gzL2S0JWw0v2GtqSa_FX

Repozitorijum: https://github.com/sstefox/Soft2017

Asistent: Stefan Anđelić @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena!
