### ISSUE TITLE
Predefinisani projekat za 60 bodova (ocene 9 i 10)

### ISSUE THREAD

**Issue by ivan248** [ftn-ai-lab/sc-2017-e2#35]
Student: Ivan Jančić  - RA157/2014

Definicija problema:

- Video zapis poseduje dve pokretne linije koje je potrebno detektovati Hough
transformacijom.
-  Cifre prolaze iza pokretnih linija.
-  Cifre koje prođu ispod prve linije treba sabrati, a cifre koje pređu ispod druge linije treba
oduzeti od konačnog rezultata.
-  Rešiti slučaj preklapajućih cifara koje istovremeno prelaze preko linije, a nalaze se
 jedna preko druge u određenoj meri.
-  Potrebno postići tačnost prepoznavanja od bar 95%.

Metodologija:

- Hough transformacija

Repozitorijum: https://github.com/ivan248/sc-2017-e2-Digit-Detection

Asistent: Kondić Miroslav @miroslavftn

**Comment by miroslavftn** [comment]
Tema odobrena!
