### ISSUE TITLE
Predefinisani projekat za 40 bodova (ocene 7 i 8)

### ISSUE THREAD

**Issue by zivko11** [ftn-ai-lab/sc-2017-e2#36]
**Student:**
Živko Stanišić RA 4/2014

**Definicija problema:**
Potrebno je izvršiti sabiranje svih cifara koje prođu ispod linije.
Liniju detektovati korišćenjem Hough transformacije.
Postići tačnost prepoznavanja od bar 90%.

**Repozitorijum:**
https://github.com/zivko11/Soft-Computing

**Asistent:** 
Stefan Anđelić @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena!
