### ISSUE TITLE
Ocitavanje uplata sa uplatnica i prebacivanje sredstava sa jednog racuna na drugi

### ISSUE THREAD

**Issue by soru23** [ftn-ai-lab/sc-2017-e2#37]
Clanovi tima: Nikola Spiric RA220/2013, Uros Zugic RA202/2013, Stefan Janjic RA200/2013
Git repozitorijum: https://github.com/soru23/SoftComputing
Asistent: @miroslavftn

-Pri izradi resenja koristili bi KNN algoritam 
-Podatke bi skupljali manuelno . Moraju se prvo obraditi pa tek onda koristiti. 
-Sto se tice validacije resenja , u fajlu ce biti sacuvani validni podaci pa bi ih uporedjivali . 

Algoritam ce ucitavati nekoliko slika elektronskih uplatnica i sa njih izvlaciti podatke koje ce kasnije koristiti za prebacivanje sredstava .

**Comment by miroslavftn** [comment]
- za sta planirate da koristite KNN
- kakvog kvaliteta ocekujete da ce biti prikupljeni podaci (rotirani, iskrivljena perspektiva, slabo osvetljeni..)
- da li cete koristiti test/train podelu skupa
- na sta ste mislili pod "Moraju se prvo obraditi pa tek onda koristiti."
- da li algoritam ucitava nekoliko slika sa istim sadrzajem ili razlicitim

Posto vas je trojica u timu, za vecu ocenu ocekuje da budu reseni i najkomplikovaniji slucajevi (da resenje radi sto razlicitijim slikama u smislu kvaliteta i sadrzaja. npr i preklapanje linije za unos i samog teksta..)

Tema je odobrena.

**Comment by soru23** [comment]
KNN ce se koristiti za prepoznavanje karaktera na slikama. Prvo ce se koristiti za prepoznavanje karaktera koristenih za trening i obucicemo algoritam. Onda ce se obuceni algoritam koristiti za prepoznavanje karaktera na slikama koje se koriste za testiranje. Podaci nece biti rotirani, niti iskrivljeni. Eventualno ce biti blago zatamnjeni. Koristicemo podelu na test i train podatke. "Moraju se prvo obraditi pa tek onda koristiti" > mislili smo da ce se najpre odraditi trening (obraditi) pa ce se onda testirati (koristiti). Algoritam ucitava slike sa razlicitim sadrzajem.

**Comment by miroslavftn** [comment]
Tema odobrena, ali nece biti moguce dobiti maksimalnu ocenu sa ovako jednostavnim skupom podataka.
