### ISSUE TITLE
Prepoznavanje nota u notnoj svesci i generisanje melodije na osnovu nota

### ISSUE THREAD

**Issue by tanjaindjic** [ftn-ai-lab/sc-2017-e2#38]
- Članovi tima:

Tanja Indjić RA145/2014
Nina Miladinović RA119/2014

- Problem koji se rešava:

Rešava se problem prepoznavanja nota u notnom sistemu kao i generisanje melodija na osnovu prepoznatih nota,

- Algoritmi koji će se koristiti:

Hjuova transformacija, konvoluciona neuronska mreža.

- Metrika za poredjenje performansi algoritama i/ili parametara algoritma:

Na osnovu broja tačno prepoznatih nota i notnih znakova.

- Podaci koji se koriste - da li su već dostupni online, da li ce se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi? 

Podaci u vidu slika notnih sistema će delom biti preuzeti sa interneta, a deo cemo same uslikati. Podaci će biti postavljeni na repozitorijum. Moguće je da će biti potrebno obraditi neke podatke.

- Na koji nacin planirate validaciju rešenja?

Validacija resenja biće izvršena za označen set podataka i to na osnovu poklapanja visine i trajanja prepoznatih tonova sa ošekivanim vrednostima.

Asistent : Miroslav Kondic @miroslavftn
 
Repozitorijum: https://github.com/tanjaindjic/Soft-Computing

**Comment by miroslavftn** [comment]
Tema je odobrena, ali imam nekoliko pitanja: 

- za sta planirate da koristite konvolucionu neurnosku mrezu
- sta sve ocekujete da sadrzi skup podataka (rotirane slike, zasumljene slike, slike loseg kvaliteta..)
- Metrika za  poredjenje performansi algoritama i/ili parametara algoritma mi nije jasna

**Comment by tanjaindjic** [comment]
Konvolucionu neurnosku mrežu planiramo da koristimo pri prepoznavanju znaka (da li je nota, povisilica, ključ, pauza, taktica...), a zatim na osnovu "isečka" sa notnim linijama koji je ton u pitanju.
Skup podataka bi obuhvatao slike različitog kvaliteta, od jasnih i čistih do mutnijih, lošijeg kvaliteta i rotiranih. 
Što se tiče metrike za poređenje performansi, proveravaćemo koliko je nota tačno prepoznato (u procentima). Za svaku notu, tačnije simbol koji se može javiti imaćemo jedinstven naziv i to ćemo koristiti pri obučavanju mreže, kao i za poređenje sa izlaznim vrednostima pri validaciji rešenja.
