### ISSUE TITLE
Prepoznavanje nutritivne vrednosti na osnovu uslikane namirnice

### ISSUE THREAD

**Issue by damianac** [ftn-ai-lab/sc-2017-e2#39]
**Ko su članovi tima?**
Dino Pokas RA 102/2014
Aleksandar Simikić RA 213/2014
Luka Damjanac RA 144/2014

**Problem koji se rešava?**
Na osnovu slike hrane, automatski se izračunava broj nutritivne vrednosti na 100g. Na taj način, može se izračunati tačan dnevni unos kalorija, proteina i sličnih nutritivnih vrednosti. Planirana je podrška oko 100 namirnica.

**Algoritmi**
Za pronalaženje namirnice će se koristiti HOG, a za prepoznavanje namirnice konvolutivna mreža.

**Metrika za poređenje performansi algoritama ili parametara algoritma**
Kao metrika će se koristiti procenat uspešnosti prepoznavanje namirnice. U metriku se ne ubacuje procenat uspešnosti prepoznavanja nutritivne vrednosti, već samo prepoznata namirnica.

**Podaci koji se koriste?**
Podatke ćemo sami dodavati na osnovu slika sa naših telefona, i slika sa interneta.

**Na koji način planirate validaciju rešenja?**
Validaciju ćemo napraviti na osnovu naših ručno dodatih podataka iz dataSet-a.

**Asistent**
Miroslav Kondić

**Repozitorijum**
https://github.com/damianac/Nutrition-value-recongnizer

**Comment by miroslavftn** [comment]
Veoma interesantna tema, evo nekoliko pitanja:

- za sta planirate da koristite HOG
- za sta planirate da koristite konvolucionu
- u cemu se konvolutivna razlikuje od Deep learning-a
- nad kojim skupom podataka cete obucavati resenje
- koliko razlicitih namirnica planirate da podrzite
- da li ce metrika za tacnost racunati posebno prepoznavanje hrane, a posebno prepoznavanje nutritivne vrednosti

Tema je odobrena, srecan rad.
