### ISSUE TITLE
Prepoznavanje entiteta sa dijagrama SQL baze podataka i generisanje njihovog JSON opisa

### ISSUE THREAD

**Issue by kockarevicivan** [ftn-ai-lab/sc-2017-e2#4]
**Članovi tima:** Ivan Kockarević, RA181/2014
**Problem koji se rešava:** Parsiranje slike dijagrama SQL baze podatak u njen JSON opis.
**Algoritam(Biblioteka):** Tesseract OCR i AForge.NET
**Metrika za poređenje performansi parametara algoritma:**  Tačnost prepoznavanja broja entiteta unutar šeme, broja kolona unutar entiteta, kao i imena i tipa kolona unutar entiteta.
**Podaci koji se koriste:** Mreže su već istrenirane, tj. trening podaci već postoje. Za test podatke će se koristiti random slike dijagrama baza podataka, pronađene online. Sakupljanje test podataka će se vršiti manuelno, bez potrebe za dodatnom obradom.
**Validacija rešenja:** Validacija rešenja će se vršiti na osnovu tačnosti prepoznavanja broja entiteta unutar šeme, broja kolona unutar entiteta, kao i imena i tipa kolona unutar entiteta.

**Link ka repozitorijumu:** [https://github.com/kockarevicivan/Soft-Computing---UML-to-JSON](https://github.com/kockarevicivan/Soft-Computing---UML-to-JSON)
**Asistent:** @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena!
