### ISSUE TITLE
Predefinisani projekat za 40 bodova (ocene 7 i 8)

### ISSUE THREAD

**Issue by muticdjordje** [ftn-ai-lab/sc-2017-e2#41]
Student: Đorđe Mutić RA65/2013

Definicija problema:

- Izvršiti sabiranje svih cifara koje prolaze ispod linije
- Liniju detektovati korišćenjem Hough transformacije
- Postići tačnost prepoznavanja od bar 90%

Repozitorijum: https://github.com/DjOka1914/soft2017

Asistent: Stefan Anđelić @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena!
