### ISSUE TITLE
Prepoznavanje likova Simpsonovih

### ISSUE THREAD

**Issue by jovananovakovic** [ftn-ai-lab/sc-2017-e2#42]
**Tim:**
Aleksandar Dobrić RA184/2014,
Jovan Dragutinović RA138/2014,
Jovana Novaković RA107/2014,
grupa 1

**Definicija problema:**
Prepoznati koji od 20 likova se pojavljuju u video snimku animirane serije Simpsonovi.

**Algoritmi:**
OpenCV za detektovanje likova i izdvajanje frejmova iz video zapisa. Za prepoznavanje konkretnog lika obučićemo konvolucionu neuronsku mrežu.

**Metrika za poređenje performansi algoritama i/ili parametara algoritma** 
Video je niz slika, pa ćemo izračunati procenat slika na kojima su likovi tačno prepoznati.

**Skup podataka:**
https://www.kaggle.com/alexattia/the-simpsons-characters-dataset

**Validacija rješenja:**
Validacija rešenja će se vršiti na osnovu test skupa sa video klipova. 

**Repozitorijum:**
https://github.com/jova1111/simpsons-recognition

**Asistent:**
@miroslavftn

**Comment by miroslavftn** [comment]
Tema odobrena. Imam nekoliko pitanja:

- da li cete pokriti slucajeve kada se na slici nalazi vise likova
> Metrika za poređenje performansi algoritama i/ili parametara algoritma
> Video je niz slika, pa ćemo izračunati procenat slika na kojima su likovi tačno prepoznati.

Znam ja da je niz, ali mi nije jasno. Ako video ima 60 fps da li ce to znaciti da je na svih 60 prepoznao/pogresio? Ojasnite detaljnije i validaciju resenja.
