### ISSUE TITLE
Prepoznavanje vrednosti kombinacije u pokeru

### ISSUE THREAD

**Issue by nemanjagavrilovic** [ftn-ai-lab/sc-2017-e2#48]
**Clanovi tima: 
N**ikola Stankovic RA92/2014, 
Nemanja Gavrilovic RA168/2014,
Nenad Milinkovic RA106/2014
**Asistent:** @miroslavkondic
Grupa sa vežbi: 1
**Definicija problema:**
Detektovati vrednost i boju karata sa slike i na osnovu njih odrediti koja je to kombinacija karata u pokeru.
**Motivacija problema:**
Pomoc novim igracima pokera da prepoznaju kolika je vrednost njihovih karata u ruci.
**Skup podataka:**
Rucno pravljen skup podataka uslikanih karata iz više uglova.
**Algoritmi:**
Unos slike u program za obradu, izdvajanje karata na slici, obrada svake karte, odredivanje vrednosti svake karte,
odredivanje boje karte, odredivanje koja je to kombinacija karata u pokeru.
**Metrika performansi algoritma:**
Broj ispravno prepoznatih karata.
**Validacija:**
Samostalna validacija rezultata.
**GitHub repository:** https://github.com/nemanjagavrilovic/SoftComputing

**Comment by miroslavftn** [comment]
Tema odobrena. Zanima me samo da li cete podrzavati vise spilova karata ili samo jedan tip? Kao i kakav skup podaataka moze da se ocekuje (rotacija, sum, perspektiva, osvetljenje..)?

**Comment by nemanjagavrilovic** [comment]
Radićemo sa 3 špila karata ,čije će slike biti pod određenim uglom,u normalnoj i obrnutoj rotaciji.
