### ISSUE TITLE
Klasifikacija belih krvnih zrnaca 

### ISSUE THREAD

**Issue by sinisa95** [ftn-ai-lab/sc-2017-e2#5]
**Ko su članovi tima?**

> Kristina Papić RA1-2014 i Siniša Božić RA192-2014 , grupa 4

**Problem koji se rešava?**

> Rešavaće se klasifikacija belih krvnih zrnaca na neutrofilne, limfocite, eozionofilne i monocite. Prvo se identifikuju leukociti iz dataset-a sa slikama, a zatim se obučava neuronska mreža za klasifikaciju leukocita u prethodne navedene grupe.

**Koji će algoritmi biti korišteni?**

> Segmentacija leukocita na osnovu boje, oblika i veličine.
> Konvoluciona neuronska mreža

**Metrika za poređenje performansi algoritama**

>  Na osnovu broja tačno prepoznatih i klasifikovanih leukocita.

**Podaci koji se koriste?**

> Podaci tj. slike su preuzete na web-u i ne moraju se obrađivati.

**Validacija rešenja?**

>Validacija će biti izvršena pomoću dataset-a koji je odvojen za testiranje neuronske mreže. Imaćemo dve grupe za test i to jedna koja je sa očiglednim primerima , a drugu gde ima više varijacija u izgledu ćelija. Preciznost će biti iskazana u procentima, tj. koliko je tačnih test slika  u odnosu na ceo skup test slika.

Repozitorijum: https://github.com/sinisa95/White-blood-cell-classification

Asistent: @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena, samo jos dodajte segmentaciju kao sto je dogovoreno.
