### ISSUE TITLE
 Prepoznavanje broja i imena autobuske linije sa LED natpisa na osnovu slika autobusa.

### ISSUE THREAD

**Issue by vlada29** [ftn-ai-lab/sc-2017-e2#53]
- Članovi tima:
  

1. Olivera Hrnjaković RA113/2014
2. Vlada Đurđević RA108/2014

- Problem koji se rešava:
Prepoznavanje broja i imena autobuske linije sa LED natpisa na osnovu slika autobusa.

- Način rešavanja problema:

     Problem se sastoji iz dva dela:

1. Izdvajanje natpisa
Prvo bi radili izdvajanje autobusa sa slike pa potom izdvajanje samog LED natpisa.
Ovde bi koristili **Canny Edge Detection** algoritam ili **Hough Line** transformaciju u zavisnosti od toga koja bi pružila bolja rešenja.

2. Čitanje samog teksta
Za ovaj deo bi koristili neuronsku mrezu obucenu u fontu koji se nalazi na LED natpisu.

- Dataset:
Dataset bi bio sačinjen delom od slika koje smo pronašli na internetu a delom od slika koje smo napravili ručno.

- Validacija:
Broj tačno prepoznatih autobuskih linija, rešenja će se porediti sa fajlom koji sadrzi tačne rezultate.

- Asistent:
Ivan Perić @ivan7792

- Repozitorijum: 

    [https://github.com/vlada29/Soft-Computing](https://github.com/vlada29/Soft-Computing)

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Obratite pažnju na sledeći element:
- Kako planirate prepoznati autobus na osnovu edge based algoritma, ili detekcije linija? Da li radite pattern matching, klasifikaciju nad datasetom edge based, ili nešto sasvim drugo? Dopunite prijavu tim delom, pre odbrane projekta.

**Comment by OljaH** [comment]
Nakon što je na sliku autobusa primenjen filter za izdvajanje plave boje (pretpostavka je da je autobus plav), primenjujemo Canny Edge Detection algoritam. Na osnovu njega dobijamo konture koje nam pomažu da pomoću njihovih osobina (širine, visine) odredimo koji je prednji deo autobusa. Takođe slično tome kasnije koristimo Canny da bi dobili ivice slova, na osnovu kojih se iseca deo koji je natpis autobusa.
