### ISSUE TITLE
Prepoznavanje bolesti lista

### ISSUE THREAD

**Issue by JelenaZoric** [ftn-ai-lab/sc-2017-e2#58]
- **Članovi tima**
Teodora Brašančević, RA 82/2014,
Jelena Zorić, RA 99/2014,
grupa 5

- **Detaljniji opis problema**
Na osnovu slike lista najpre se vrši prepoznavanje vrste biljke (projekat će se ograničiti na 2 vrste - vinovu lozu i krompir), a zatim identifikacija bolesti (projekat će se ograničiti na jednu bolest - plamenjaču). Nakon identifikacije bolesti, ideja je da program predloži način lečenja prepoznate bolesti, kako bi imao komercijalnu primenu.

- **Algoritmi koji se koriste**
OpenCV,
KNN ili neuronska mreža za prepoznavanje vrste biljke i 
KMeans za identifikaciju bolesti na osnovu boje

- **Metrika za poređenje performansi**
Kao metrika će se koristiti procenat uspešnosti prepoznavanja vrste i bolesti.

- **Podaci koji će se koristiti**
Koristiće se slike lista koje će uglavnom biti potrebno obraditi pre dalje primene.

- **Validacija**
Za validaciju vrste biljke koristiće se setovi trening i test podataka. Za validaciju bolesti koristiće se set slika koje će imati ručno označenu vrstu bolesti, a zatim će se vršiti poređenje sa dobijenim rezultatima. 

Repozitorijum: https://github.com/JelenaZoric/BolestiLista

Asistent: Ivan Perić, @ivan7792

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

U prijavu samo napišite za koje ste se bolesti biljaka konkretno odlučile, a koje mogu da se vide sa lista.
