### ISSUE TITLE
Prepoznavanje vremena na analognim satovima u realnom vremenu 

### ISSUE THREAD

**Issue by timotej-orcic** [ftn-ai-lab/sc-2017-e2#6]
**Članovi tima:**
- Nenad Pijanić, RA-105/2014
- Goran Rajić, RA-96/2014
- Timotej Orčić, RA-194/2014

**Problem koji se rešava (detaljniji opis):**
- Pomoću kamere (mobilnog telefona) prepoznavaćemo vreme prikazano na analognim satovima praćenjem položaja kazaljki u realnom vremenu i prikazivati dato vreme u digitalnom formatu.

**Algoritam/algoritmi koji će se koristiti:**
- Hough Transform algoritam (Circle i Ellipse) za izdvajanje krugova i elipsi (unutrašnje površine sata) i standardnu (Standard) varijantu datog algoritma za izdvajanje kazaljki sata
- Canny Edge Detection algoritam za izdvajanje ivica sata
- Convoulutional neural network - neuronska mreža koju ćemo obučiti da prepoznaje različite satove iz različitih uglova u realnom vremenu

**Metrika za poređenje performansi algoritama i/ili parametara algoritma:**
- Poznati su željeni izlazi (sati, minuti, sekunde). Imaćemo deo programa koji će ispisivati prepoznato vreme u digitalnom formatu i sa kojom tačnošću je to vreme određeno našim algoritmom.

**Podaci koji se koriste:**
- Podaci će biti prikupljeni manuelno (našom kamerom).

**Na koji način planirate validaciju rešenja?**
- Neuronska mreža mora biti obučena da prepozna različite satove iz različitih uglova, sa različitim osvetljenjem. Manuelno ćemo moći da validiramo naše rešenje čitajući vreme sa datih satova i tako uporedimo sa rešenjem koje ispisuje naš program.

Asistent: @miroslavftn 
Repozitorijum: https://github.com/timotej-orcic/SOFT-2017

**Comment by miroslavftn** [comment]
Tema odobrena srecan rad. Tezina vaseg zadatka ce zavisiti od skupa podataka, stoga imam nekoliko pitanja: 

- da li su svi satovi imaju istu pozadinu?
- da li ce biti uslikani iz razlicite perspektive?
- da li ce mozda biti i rotirani? Ako hoce za koliko makimalno stepeni? 
- da li ce svi satovi imati iste brojeve (rimski i arapski)

Kada kazete da koristite konvolutivnu neuronsku mrezu za prepoznavanje satova, da li to znaci samo za detakciju sata na slici ili i ocitavanje tacnog vremena?

**Comment by timotej-orcic** [comment]
Pozdrav,

Za početak, hvala što učestvuješ na našem projektu! :)

Naš cilj kao ekipe jeste ocena 10, pa smo mislili da uzmemo komplikovaniju
varijantu, tj. da radimo obradu video snimka u realnom vremenu,
gde ćemo pomoću neuronske mreže prepoznavati površine satova a i učitavati
tačno vreme. Što se tiče pozadine, perspektive i rotacije
isto nam je želja da naša aplikacija podržava što je moguće složeniju
varijantu, kako zbog ocene, tako i zbog našeg boljeg upliva u samu
tematiku,
posebno u vezi sa neuronskim mrežama.

Taman možemo odma da te pitamo, da li ovako specificiran zadatak vredi za
ocenu 10, i ako ne vredi šta bismo još mogli da ubacimo u naš projekat?

Hvala unapred i srećni praznici,
Timotej Orčić

2017-12-27 15:02 GMT+01:00 Miroslav Kondic <notifications@github.com>:

**Comment by miroslavftn** [comment]
Sa svim gore navedenim izazovima i video snimkom vredi za 10.

**Comment by timotej-orcic** [comment]
Super, hvala ti! :)

**Comment by timotej-orcic** [comment]
Pozdrav,

Imamo samo jedno kratko pitanje za tebe kao tim.

Da li mozemo da koristimo dati algoritam pri implementaciji nase neuronske
mreze?
Rec je o YOLO algoritmu koji je, kolko smo istrazili, zaista odlican u
real-time prepoznavanju objekata.

Evo reference na samu ideju algoritma:
https://pjreddie.com/media/files/papers/yolo.pdf
I takodje preview na youtube-u: https://www.youtube.com/watch?v=VOC3huqHrss

Hvala unapred :)

Timotej Orcic

**Comment by miroslavftn** [comment]
Mozete, samo naucite dobro kako on radi :)

**Comment by timotej-orcic** [comment]
Važi, hvala ti. :)
