### ISSUE TITLE
Klasifikacija zmija na otrovne i neotrovne na osnovu slike

### ISSUE THREAD

**Issue by smiljana95** [ftn-ai-lab/sc-2017-e2#68]
## Članovi tima
Smiljana Dragoljević, RA 36/2014,
Jelena Stanarević, RA 143/2014,
grupa 7

## Detaljniji opis problema
Klasifikacija zmija sa slika će vršiti na otrovne i neotrovne, na osnovu odgovarajućih dimenzija glave.  

## Algoritmi koji se koriste
K-Nearest neighbors (KNN) i neuronska mreža.

## Metrika za poređenje performansi
Gledaće se procenat uspešnost klasifikacije.

## Validacija
Skup podataka će biti podeljen na trening, validacioni i test dataset. Na osnovu trening podataka će se obučavati neuralna mreža i klasifikator za KNN algoritam, a hiperparametri će se podešavati na osnovu validacionih podataka. Performansa će se meriti na osnovu test podataka.

## Ostalo
[Repozitorijum](https://github.com/jelenastanarevic/softcomputing)

Asistent: Ivan Perić, @ivan7792

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Samo jedna napomena. Pristup gde se koriste za konvolutivne neuronske mreže može biti samo za maksimalnu ocenu 8, ukoliko nemate nikakvu dodatnu pripremu ili analizu podataka ili rezultata. 
Kod konvolutivnih NN je dovoljno da pustite dataset sa slikama u mrežu i da ceo projekat bude gotov.

Za višu ocenu je potrebno neko procesiranje slike i klasifikacija nečim drugim (osim CNN). Možete procesirati fotografije glava zmija i klasifikovati na osnovu oblika ili šara (ili oboje). Uz to proširenje projekat može biti za maksimalnu ocenu.
