### ISSUE TITLE
Drift AI Q-learning

### ISSUE THREAD

**Issue by ljmocic** [ftn-ai-lab/sc-2017-e2#69]
**Autor:** Ljubiša Moćić, RA91/2014, grupa 3

**Asistent:** Ivan Perić @ivan7792

**Cilj projekta:** Implementacija i istraživanje reinforcement learning algoritama.

**Opis projekta:**
- **_Osnova:_** Projekat je zamišljen kao pokušaj kreiranja autonomnog agenta koji je sposoban da savlada veštinu Drift-a na nivou sposobnosti profesionalnog vozača.
- **_Okruženje:_** Need for Speed Carbon, staza Kimei Temple. 
- **_Važni faktori:_** Za drift su bitne promenljive kao što su: brzina ulaska u krivinu pri aktiviranju ručne kočnice i uspešno kontrolisanje vozila pri klizanju, bez udarca u zid.
- **_Nagrada:_** Na osnovu vremena klizanja, broja krivina u kojima se zaredom održi drift i brzine, se dodeljuju bodovi. Bodovi ce predstavljati nagradu na osnovu koje će algoritam shvatiti u kom stanju je bitno primeniti određene akcije.

**Algoritam:**
- _**Q-Learning**_ pri čemu će se u obzir uzeti stanja u kojima se vozilo nalazi i trenuci u kojima će algoritam regovati da izvrši akciju koja će dovesti do veće nagrade ili boljeg stanja, pri cemu će nagradu predstavljati bodovi.

**Implementacija:**
- **_Obrada frejmova:_** OpenCV, NumPy
- **_Detekcija nagrada:_** Neuronske mreze, Tesseract
- **_Automatizacija epizoda:_** PyAutoGUI
- **_Prilagođavanje igre:_** NFSCExOpts mod

**Metrika za poređenje performansi algoritama i/ili parametara algoritma:** 
Poređenje performansi parametara algoritma će se vršiti poređenjem maksimalnog rezultata epizoda u istim delovima staze nakon određenog broja iteracija.

**Podaci koji se koriste:** Generisani tokom izvršavanja akcija unutar igre.

**Validacija rešenja:** Empirijski, uz pomoć prikaza izvršavanja skripte i/ili prikaza video snimka prethodno istreniranog agenta. 

**Repozitorijum:** https://github.com/ljmocic/drift-ai

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.
