### ISSUE TITLE
Prepoznavanje ljudske kože na slici

### ISSUE THREAD

**Issue by Kemono995** [ftn-ai-lab/sc-2017-e2#7]
Članovi tima:

    Miloš Ostojić RA140/2014
    Aleksandar Jovanović RA146/2014

Problem koji se rešava (detaljniji opis)

    Prepoznavanje ljudske kože na slici. Proizvod su rezultati kombinacija različitih modela boja, algoritama, threshold-a i stepena erozije i dilatacije i njihovo međusobno poređenje.

Algoritam/algoritmi koji će se koristiti

Modeli boja:
    -RGB
    -HSV  

Algoritmi:
   - Decision tree
   - KNN
   - Konvolutivna neuronska mreža

    -Dilatacija i erozija 

Metrika za poređenje performansi algoritama i/ili parametara algoritma

    Međusobno poređenje rezultata u vidu binarnih slika.

Podaci koji se koriste

    Koristiće se Data set kreiran kombinovanjem više Data set-ova pronađenih online.

Na koji način planirate validaciju rešenja?

    Validacija pojedinačnog rešenja će se raditi manuelno kroz prikaz originalne slike i binarne slike rezulata dobijene tim skupom komponenti.
    Razlike u rezultatima različitih skupova komponenti biće dostupne u procentualnom obliku u tabelama razlika, i u obliku druge binarne slike koja predstavlja razlike u rezultatima ta dva skupa komponenti. 

Repozitorijum:
https://github.com/Kemono995/Soft-Computing-2018

Asistent: @miroslavftn

**Comment by miroslavftn** [comment]
Tema odobrena, ali iskreno ne razumem sta je cilj projekta. 
- Da li ce se prepoznavanje koze svesti na odredjivanje boje koze?
- Kako onda planirate da validirate sa binarnim slikama? 
- Za sta planirate da koristite eroziju i dilataciju?
- Ako dobijemo da se nalazi koza na slici, sta smo sa tim hteli da pokazemo?

**Comment by Ostoja** [comment]
- Erozija i dilatacija će biti korišćene za eliminisanje false-positive regiona kože.
- Validacija bi uključivala poređenje rezultata šta je koji pristup prepoznao kao kožu, i upoređivanje sa originalnom slikom.
- Dinamički bi se određivala koja je boja kože na slici, većina primera koje smo pronašli polazi sa unapred zadatam threshold-om za boju kože (najčešće za white-caucasian).
