### ISSUE TITLE
Procena prinosa jagoda

### ISSUE THREAD

**Issue by VioletaMarceta** [ftn-ai-lab/sc-2017-e2#88]
- **Članovi tima:** 
Jelena Vulin ra112/2014
Violeta Marčeta ra83/2014
grupa 5

-  **Detaljniji opis problema:**
Na osnovu slike najpre se vrši odvajanje biljke od zemlje, a zatim se svakoj biljci pojedinačno određuje položaj i nakon toga na svakom delu slike brojimo plodove.

- **Algoritmi koji se koriste:**
OpenCV i 
segmentacija boje za odvajanje biljke od zemlje i ploda od lista biljke

- **Metrika za poređenje performansi:**
Koristi se procenat uspešno procenjenih prinosa

- **Podaci koji će se koristiti:**
Slike biljaka jagode koje ćemo preuzeti sa interneta

- **Validacija:**
Za validaciju procene prinosa koristiće se set slika sa ručno izbrojanim brojem plodova, a zatim će se vršiti poređenje sa dobijenim rezultatima.

Repozitorijum: https://github.com/vjelena/projekatSoft

Asistent:  Ivan Perić, @ivan7792

**Comment by ivan7792** [comment]
Lepa ideja. Tema odobrena i srećan rad.

Obratite pažnju na to da morate segmentirati svaku biljku i odvojiti ih ako su međusobno blizu, kao što je recimo [ovde ](https://docs.opencv.org/3.3.1/d3/db4/tutorial_py_watershed.html) odrađeno.

**Comment by ivan7792** [comment]
Pozdrav Jelena i Violeta,

Nedostaje adresa github repozitorijuma na kome se nalazi source kod vaseg projekta. Molim vas da ga dodate ako planirate braniti u ovom roku.
