### ISSUE TITLE
Konvertovanje slike u tekst

### ISSUE THREAD

**Issue by majagulan** [ftn-ai-lab/sc-2017-e2#9]
**Ko su članovi tima? Ime, prezime, broj indeksa...**
Smiljana Tedić (RA94/2014) i Maja Gulan (RA35/2014)

**Problem koji se rešava (detaljniji opis)**
Rešavaćemo problem konvertovanja slike u tekst prepoznajući engleski alfabet. Prvo se identifikuje svako slovo alfabeta i specijalni znakovi iz dataset-ova sa slikama, a zatim se obučava program.

**Algoritam/algoritmi koji će se koristiti**
Template Matching strategija za prepoznavanje karaktera.

**Metrika za poređenje performansi algoritama i/ili parametara algoritma**
Na osnovu braja tačno konvertovanih slika.

**Podaci koji se koriste - da li su već dostupni online, da li će se skupljati automatski ili manuelno, da li se moraju prvobitno obraditi?**
Biće korišćeni data set-ovi alfabeta, a kreiraćemo ih kombinovanjem par data set-ova dostupnih online. 

**Na koji način planirate validaciju rešenja?**
Validacija će biti izvršena manuelno poredeći izabranu sliku koju želimo konvertovati i ispisan tekst. 

**Repozitorijum:**
https://github.com/majagulan/Converting-image-to-text

**Asistent:** @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Tema odobrena, srecan rad!
